#!/usr/bin/env node

// Demo script for eBay Listing Monitor
// This shows how the application works without requiring real API credentials

const fs = require('fs');
const path = require('path');

console.log('🎬 eBay Listing Monitor - Demo Mode');
console.log('===================================');

// Create demo search criteria
const demoCriteria = {
    keyword: "vintage camera",
    category: "625",
    condition: "3000",
    minPrice: "50",
    maxPrice: "500",
    minBids: "1",
    maxResults: "10",
    email: "demo@example.com"
};

console.log('\n📝 Demo Search Criteria:');
console.log(JSON.stringify(demoCriteria, null, 2));

// Save demo criteria to file
try {
    fs.writeFileSync('search-criteria.json', JSON.stringify(demoCriteria, null, 2));
    console.log('\n✅ Demo criteria saved to search-criteria.json');
} catch (error) {
    console.log(`❌ Error saving demo criteria: ${error.message}`);
}

// Create demo listings data
const demoListings = [
    {
        title: "Vintage Canon AE-1 Program 35mm Camera",
        price: "125.50",
        bids: "3",
        endTime: new Date(Date.now() + 30 * 60 * 1000).toISOString(),
        condition: "Used",
        url: "https://www.ebay.com/itm/vintage-canon-ae1",
        image: "https://example.com/camera1.jpg",
        seller: "camera_collector",
        shipping: "Free"
    },
    {
        title: "Nikon F3 35mm Film Camera with 50mm Lens",
        price: "275.00",
        bids: "7",
        endTime: new Date(Date.now() + 45 * 60 * 1000).toISOString(),
        condition: "Very Good",
        url: "https://www.ebay.com/itm/nikon-f3-camera",
        image: "https://example.com/camera2.jpg",
        seller: "film_enthusiast",
        shipping: "15.00"
    },
    {
        title: "Leica M3 Rangefinder Camera Body Only",
        price: "450.00",
        bids: "12",
        endTime: new Date(Date.now() + 20 * 60 * 1000).toISOString(),
        condition: "Good",
        url: "https://www.ebay.com/itm/leica-m3-rangefinder",
        image: "https://example.com/camera3.jpg",
        seller: "leica_specialist",
        shipping: "25.00"
    }
];

console.log('\n📋 Demo Listings Found:');
demoListings.forEach((listing, index) => {
    const timeLeft = Math.floor((new Date(listing.endTime) - new Date()) / 60000);
    console.log(`\n${index + 1}. ${listing.title}`);
    console.log(`   💰 Price: $${listing.price}`);
    console.log(`   🔢 Bids: ${listing.bids}`);
    console.log(`   ⏰ Ends in: ${timeLeft} minutes`);
    console.log(`   📦 Condition: ${listing.condition}`);
    console.log(`   🚚 Shipping: $${listing.shipping}`);
    console.log(`   🔗 Link: ${listing.url}`);
});

// Generate demo email content
console.log('\n📧 Demo Email Notification:');
console.log('============================');
console.log('To: demo@example.com');
console.log('Subject: 🔔 eBay Alert: 3 listing(s) ending soon!');
console.log('');
console.log('eBay Listing Alert');
console.log('==================');
console.log('');
console.log('3 listing(s) ending soon for "vintage camera"');
console.log('');
demoListings.forEach((listing, index) => {
    const timeLeft = Math.floor((new Date(listing.endTime) - new Date()) / 60000);
    console.log(`${index + 1}. ${listing.title}`);
    console.log(`   Price: $${listing.price}`);
    console.log(`   Bids: ${listing.bids}`);
    console.log(`   Condition: ${listing.condition}`);
    console.log(`   Ends in: ${timeLeft} minutes`);
    console.log(`   Link: ${listing.url}`);
    console.log('');
});

console.log('Search criteria: Keyword: "vintage camera", Category: 625, Condition: Used, Price: $50 to $500, Min Bids: 1');
console.log('');
console.log('This alert was generated by eBay Listing Monitor');

console.log('\n🎯 How It Works:');
console.log('===============');
console.log('1. User sets search criteria on the web page');
console.log('2. Criteria are saved locally and on the server');
console.log('3. Cron job runs every hour');
console.log('4. eBay API is called with the saved criteria');
console.log('5. Listings ending within the next hour are found');
console.log('6. Email notification is sent with direct links');
console.log('7. User can click links to view listings on eBay');

console.log('\n🚀 Next Steps:');
console.log('==============');
console.log('1. Run: npm install');
console.log('2. Copy env.example to .env');
console.log('3. Add your eBay API credentials to .env');
console.log('4. Add your email credentials to .env');
console.log('5. Run: npm start');
console.log('6. Open: http://localhost:3000');
console.log('7. Set your own search criteria');
console.log('8. Wait for email notifications!');

console.log('\n📚 For more details, see README.md');
